### ISSUE TITLE
关于将源码和demo整合

### ISSUE THREAD

**Issue by JianghaoPi** [zrk1000/spring-boot-mvc-ueditor-qiniu#1]
我将您的源码和demo整合在一起成功了，但是我有个疑问，那就是如何把application中的那个controller移到controller.java中，使得application中只剩下
```
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }   
```
这一个函数呢？spring初学者，希望作者能帮帮忙，解解惑。

**Comment by zrk1000** [comment]
#1 在application类所在的包或子包中的Controller都会被spring boot扫描，可以参考 http://projects.spring.io/spring-boot/#quick-start

**Comment by zhoudianyou** [comment]
资讯一下使用这个插件相关的问题，七牛那边需要设置那些参数，我自己在七牛的新建了存储，但是配置上边就是不好使！！！ io 错误

**Comment by zrk1000** [comment]
#3 已更新了七牛sdk版本，支持配置七牛服务器区域Zone
