### ISSUE TITLE
快来看我。。。

### ISSUE THREAD

**Issue by James200883** [zrk1000/spring-boot-mvc-ueditor-qiniu#2]
Run AS 启动可以上传图片，为啥部署到tomcat就不行了？404找不到路径。。。

**Comment by zrk1000** [comment]
#2 在Application中使用@ComponentScan注解配置扫描com.baidu包
@ComponentScan(basePackages = {"com.zrk","com.baidu"})

**Comment by James200883** [comment]
加了喔！亲，我是clone您的代码跑的。run as试了可以了之后，就部署到tomcat上去了，就“请求后台配置项http错误，上传功能将不能正常使用！”这个错了！您有木有部署到tomcat上能跑的demo，发我一份呗！好急好急，先行谢过了！

**Comment by James200883** [comment]
不用发啦，我实现啦！哈哈。。。非常感谢你的这个demo！

**Comment by zrk1000** [comment]
#2 应该是用tomcat部署 URL中多了层项目名  而ueditor.config.js中的配置URL没有改导致的
