### ISSUE TITLE
关于使用ueditor 工具遇到的一些问题

### ISSUE THREAD

**Issue by zhoudianyou** [zrk1000/spring-boot-mvc-ueditor-qiniu#3]
@zrk1000  最近在使用这个插件，发现替换自己的七牛账号，遇到了相关的问题，替换我自己的七牛账号遇到了上传，io错误 具体看了一下代码，发现 ：error:incorrect zone, please use up-z1.qiniu.com
区域不支持，最后在尝试换区重新创建解决此问题，使用本插件必须使用  七牛的 华东区 !-_-相当吐血，是否可以考虑支持一下新版本的七牛sdk ？

**Comment by zrk1000** [comment]
@zhoudianyou  已更新了七牛sdk版本，支持配置七牛服务器区域Zone

**Comment by zhoudianyou** [comment]
感谢反馈很快
